### PR TITLE
Changed plugin start on a client

### PR DESCRIPTION
**Pull request by DmitryBelichack**
Client side plugin start filter changed from condition to plugin naming convention mechanism
https://nuxtjs.org/docs/2.x/directory-structure/plugins/#name-conventional-plugin

### CODE REVIEW

**Comment by potato4d** [comment]
@DmitryBelichack 
Could you run ci test?

**Comment by DmitryBelichack** [comment]
Sure! Done.

**Review by potato4d — APPROVED** [review]
LGTM

**Comment by potato4d** [comment]
@all-contributors add DmitryBelichack code

**Pull request merged**
